#!/usr/bin/env python3
r"""
Turn an mpi_bench diagnostic run into the setup-section latency table.

Parses the output of test5/run_mpi_diag.slurm, which runs test5/mpi_bench.c
under a series of launch idioms and transports and prints, per case:

    ping-pong latency (8B, rank0<->rank1):     0.25 us
    bandwidth (8MB pairs):                     8.73 GB/s
    allreduce (8B, 2 ranks):                   0.38 us

A case that deadlocks prints ">>> TIMED OUT" instead and is rendered as a
spanned "hangs" row rather than dropped -- the default intra-node transport
hanging is why the multi-node jobs launch the way they do, so it is a result.

Cases are grouped by rank placement (intra-node / inter-node / multi-node) with
a rule between groups, in the order they appear in the log.

Writes thesis/figures/<tag>.tex. Regenerate rather than editing that file.
"""

import argparse
import os
import re
import sys

SECTION = re.compile(r"^=+\s*(.+?)\s*=+\s*$")
LAT = re.compile(r"ping-pong latency \([^)]*\):\s*([\d.]+)\s*us")
BW = re.compile(r"bandwidth \([^)]*\):\s*([\d.]+)\s*GB/s")
AR = re.compile(r"allreduce \(8B,\s*(\d+) ranks\):\s*([\d.]+)\s*us")
CASE = re.compile(r"^([A-Z])\.\s*(.*)$")

# The headings are written for the diagnostic, not for the thesis: they carry
# expectations ("expected to hang") and asides that do not belong in a table.
# Keyed on the case letter, with the raw heading as the fallback so a new case
# still renders instead of vanishing.
TRANSPORT = {
    "A": r"\texttt{mpirun}, one container",
    "B": r"\texttt{srun}+pmix, default",
    "C": r"vader, emulated single-copy",
    "D": r"\texttt{btl=tcp,self}",
    "E": r"\texttt{pml=ucx}",
    "F": r"\texttt{pml=ucx}, no shared memory",
    "G": r"default",
    "H": r"\texttt{pml=ucx}",
    "I": r"\texttt{btl=tcp,self}",
    "J": r"\texttt{pml=ucx}",
}

# Placement is the first comma-separated field of the heading; these normalize
# its wording for the table column.
PLACEMENT = {
    "intra-node": "1 node, 2 ranks",
    "inter-node": "2 nodes, 1 rank each",
    "2 nodes x 2 ranks": "2 nodes, 2 ranks each",
}


def parse(path):
    """[(letter, placement, transport, lat, bw, ar_ranks, ar)] in log order."""
    cases, cur = [], None
    with open(path, errors="replace") as fh:
        for line in fh:
            m = SECTION.match(line.rstrip())
            if m:
                head = m.group(1)
                if head == "DONE":
                    cur = None
                    continue
                c = CASE.match(head)
                if not c:
                    cur = None
                    continue
                letter, rest = c.group(1), c.group(2)
                placement = rest.split(",", 1)[0].strip()
                cur = {"letter": letter, "raw": rest,
                       "placement": PLACEMENT.get(placement, placement),
                       "transport": TRANSPORT.get(letter),
                       "lat": None, "bw": None, "ar": None, "ar_ranks": None,
                       "hung": False}
                cases.append(cur)
                continue
            if cur is None:
                continue
            if "TIMED OUT" in line:
                cur["hung"] = True
            for rx, key in ((LAT, "lat"), (BW, "bw")):
                m = rx.search(line)
                if m:
                    cur[key] = float(m.group(1))
            m = AR.search(line)
            if m:
                cur["ar_ranks"], cur["ar"] = int(m.group(1)), float(m.group(2))
    if not cases:
        sys.exit("no '===== X. ... =====' case headings found in %s -- is this "
                 "an mpi_bench diagnostic log?" % path)
    for c in cases:
        if c["transport"] is None:
            # Strip the parenthetical aside, keep whatever describes the transport.
            c["transport"] = re.sub(r"\s*\(.*\)\s*$", "",
                                    c["raw"].split(",", 1)[-1]).strip()
    return cases


TEMPLATE = r"""% ------------------------------------------------------------------------
%  MPI transport measurements on the TU Berlin HPC.
%  Generated by scripts/mpi_latency_table.py from SOURCE -- regenerate
%  rather than edit. Include with \input{figures/TAG}
%  Needs \usepackage{booktabs}.
% ------------------------------------------------------------------------
\begin{table}[htbp]
    \centering
    \footnotesize
    \begin{tabular}{llrrr}
        \toprule
        placement & transport & ping-pong & bandwidth & allreduce \\
                  &           & [$\mu$s]  & [GB/s]    & [$\mu$s]  \\
        \midrule
ROWS        \bottomrule
    \end{tabular}
    \caption{MPI performance between two nodes of the TU Berlin HPC, measured
        with \texttt{mpi\_bench.c} from inside the NGPB container. Ping-pong and
        allreduce use 8\,B messages, bandwidth 8\,MB. Ping-pong is always rank 0
        to rank 1, which is a same-node pair in the last row.}
    \label{tab:LABEL}
\end{table}
"""


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("log", help="the mpidiag .out file")
    ap.add_argument("--thesis", default="thesis")
    ap.add_argument("--tag", default="mpi_latency_table")
    ap.add_argument("--cases", default=None,
                    help="comma-separated case letters to keep, in log order "
                         "(default: all of them)")
    args = ap.parse_args()

    cases = parse(args.log)
    if args.cases:
        want = [c.strip().upper() for c in args.cases.split(",")]
        missing = [w for w in want if w not in {c["letter"] for c in cases}]
        if missing:
            sys.exit("no such case(s) in %s: %s" % (args.log, ", ".join(missing)))
        cases = [c for c in cases if c["letter"] in want]

    rows, prev = [], None
    for c in cases:
        if prev is not None and c["placement"] != prev:
            rows.append("        \\midrule\n")
        prev = c["placement"]
        if c["hung"] or c["lat"] is None:
            body = r"\multicolumn{3}{c}{deadlocks}"
        else:
            ar = ("---" if c["ar"] is None else
                  "%.2f" % c["ar"] if c["ar_ranks"] == 2 else
                  "%.2f (%d ranks)" % (c["ar"], c["ar_ranks"]))
            body = "%.2f & %.2f & %s" % (c["lat"], c["bw"], ar)
        rows.append("        %s & %s & %s \\\\\n"
                    % (c["placement"], c["transport"], body))

    out = os.path.join(args.thesis, "figures", args.tag + ".tex")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as fh:
        fh.write(TEMPLATE
                 .replace("SOURCE", args.log)
                 .replace("ROWS", "".join(rows))
                 # The other labels in the setup chapter are hyphenated.
                 .replace("LABEL", args.tag.replace("_", "-"))
                 .replace("TAG", args.tag))

    for c in cases:
        print("  %s  %-22s %-46s lat %-7s bw %-7s allreduce %s"
              % (c["letter"], c["placement"],
                 re.sub(r"\\texttt\{(.*?)\}", r"\1", c["transport"]),
                 "hang" if c["hung"] else "%.2f" % c["lat"],
                 "hang" if c["hung"] else "%.2f" % c["bw"],
                 "hang" if c["hung"] else
                 "%.2f (%d ranks)" % (c["ar"], c["ar_ranks"])))
    print("\nwrote %s" % out)


if __name__ == "__main__":
    sys.exit(main())
