#!/usr/bin/env python3
"""
Turn a source x target leaf-size sweep into a pgfplots figure: time against each
leaf axis, at fixed theta and p.

This is the figure that justifies decoupling the two trees. Before the split the
sweep could only walk the src == tgt diagonal, on which 64 and 256 came out
near-identical -- 256 was winning the far field and 64 the near field, and the
diagonal averaged the two effects into a flat region with no visible optimum.
Sweeping the axes independently separates them:

    left panel   x = source leaf, one line per target leaf
    right panel  x = target leaf, one line per source leaf

Each line should show an interior minimum. Small source leaves cut the near-field
radius the MAC tests against, but too small and the tree deepens and the M2L list
grows; large target leaves cut the target box count and hence the M2L pair count,
but too large and each l2p_p2p block strides over more points than it can hold in
registers.

theta and p are held FIXED -- this figure is about the leaf axes only. If the CSV
carries more than one value of either, pass --mac / --order to choose.

Writes, relative to the thesis directory:
    figures/data/<tag>.dat        one row per (source, target) configuration
    figures/data/<tag>_ref.tex    reference values as macros
    figures/<tag>.tex             the figure, \\input-able like the others

Sibling of plot_fmm_sweep.py, which draws the accuracy-against-work figure. That
one puts outcomes on both axes and encodes the parameters; this one puts a
parameter on x and has no error axis at all, so they share the CSV layer
(fmm_csv.py) and nothing else.
"""

import argparse
import os
import re
import statistics
import sys

import fmm_csv

# Ordered by lightness so the ramp survives greyscale printing, and spaced enough
# to stay distinguishable under the common CVD types. Six entries covers the
# target axis (128..4096); the source axis uses the first four.
RAMP = [
    ("leafA", "1B3A6B"),
    ("leafB", "1F77B4"),
    ("leafC", "17A398"),
    ("leafD", "7EA83D"),
    ("leafE", "E8A33D"),
    ("leafF", "C1272D"),
]
MARKS = ["*", "square*", "triangle*", "diamond*", "pentagon*", "oplus*"]


LEAF_MACROS = ["leafMolecule", "leafNatoms", "leafMac", "leafOrder",
               "leafRepeats", "leafBest", "leafNaiveNote", "leafMachine"]


def localise(text, tag):
    r"""Make macros, labels and legend names unique to this figure.

    Same reason as in plot_fmm_sweep.py: more than one of these can appear in a
    single document, and \def is global, so shared names would have every caption
    read whichever figure was typeset last.
    """
    sfx = "".join(c for c in tag if c.isalpha())
    # (?![A-Za-z]) is load-bearing: a LaTeX control sequence ends at the
    # first non-letter, so a plain replace of \\leafMac also rewrites the
    # \\leafMachine that starts with it -- which it did, silently producing
    # \\leafMacleafsweepvybhine and an undefined macro in the caption.
    for name in LEAF_MACROS:
        text = re.sub(r"\\" + name + r"(?![A-Za-z])",
                      "\\\\" + name + sfx, text)
    return text.replace("SFX", sfx).replace("TAG", tag)


def pick_fixed(points, key, wanted, label):
    """Reduce to a single value of a held-fixed axis."""
    present = sorted({d[key] for d in points})
    if wanted is not None:
        chosen = type(present[0])(wanted)
        if chosen not in present:
            sys.exit("no rows with {} = {} (have {})".format(
                label, wanted, ", ".join("{:g}".format(v) for v in present)))
        return [d for d in points if d[key] == chosen], chosen
    if len(present) > 1:
        sys.exit("CSV carries {} values of {} ({}) -- this figure holds it fixed, "
                 "so pass --{} to choose".format(
                     len(present), label,
                     ", ".join("{:g}".format(v) for v in present), label))
    return points, present[0]


FIGURE_TEMPLATE = r"""% ------------------------------------------------------------------------
%  FMM leaf-size sweep: the two tree leaf sizes, swept independently.
%  Generated by scripts/plot_leaf_sweep.py -- regenerate rather than edit.
%  Include with \input{figures/TAG}
%  Needs \usepackage{pgfplots} in the preamble.
% ------------------------------------------------------------------------
\input{figures/data/TAG_ref}

\pgfplotsset{compat=1.16}
\usepgfplotslibrary{groupplots}

% Keep only the rows where column #1 equals #2.
\pgfplotsset{
  discard if not/.style n args={2}{
    x filter/.code={%
      \edef\tempa{\thisrow{#1}}\edef\tempb{#2}%
      \ifx\tempa\tempb\else\def\pgfmathresult{inf}\fi
    }
  }
}

COLORDEFS

\begin{figure}[!htb]
\centering
\begin{tikzpicture}
\begin{groupplot}[
    group style={
      group size=2 by 1,
      horizontal sep=1.5cm,
    },
    width=7.4cm, height=5.6cm,
    xmode=log, log basis x=2,
    ylabel={energy calculation [s]},
    xlabel style={font=\footnotesize},
    ylabel style={font=\footnotesize},
    tick label style={font=\scriptsize},
    title style={font=\footnotesize, yshift=-0.4ex},
    grid=both,
    major grid style={black!12},
    minor grid style={black!5},
    minor tick num=0,
    ymin=YMIN, ymax=YMAX,
    legend columns=LEGCOLS,
    legend style={draw=none, font=\footnotesize, column sep=0.6em},
]
PANELS
\end{groupplot}
\end{tikzpicture}

\vspace{0.4ex}
\ref{leafsweeplegendsrcSFX}

\vspace{0.2ex}
\ref{leafsweeplegendtgtSFX}

\caption[FMM leaf sizes swept independently]{\textbf{The two FMM tree leaf sizes
    on \leafMolecule{} (\leafNatoms{} atoms), swept independently at
    $\theta = \leafMac{}$ and $P = \leafOrder{}$.} \leafRepeats{}-repeat median
    times. \emph{Left:} against the \emph{source} (atom) leaf size, one line per
    target leaf size. \emph{Right:} against the \emph{target} (surface) leaf
    size. Fastest: \leafBest{}.\leafNaiveNote\leafMachine}
\label{fig:TAG}
\end{figure}
"""

PANEL_TEMPLATE = r"""
\nextgroupplot[xlabel={$n_{leaf,AXIS}$}, xtick={XTICKS}, xticklabels={XTICKLABELS}LEGENDOPT]
NAIVE
SERIESLEGEND"""

SERIES_TEMPLATE = r"""  \addplot[color=COLOR, mark=MARK, mark size=1.3pt, line width=0.9pt FORGET]
    table[x=XCOL, y=time, discard if not={FILTCOL}{FILTVAL}] {figures/data/TAG.dat};
ENTRY"""


def build_panel(axis, xcol, filtcol, values, points, tag, legend_name, naive_t):
    """One panel: x = xcol, one line per value of filtcol.

    Both panels get their OWN legend. They share the colour ramp but their series
    are different axes -- leafA is the smallest target leaf on the left and the
    smallest source leaf on the right -- so a single shared legend would label
    half the figure wrongly.
    """
    xs = sorted({d[xcol] for d in points})
    sub = "tgt" if filtcol == "tleaf" else "src"
    series = []
    for i, v in enumerate(values):
        colour, _ = RAMP[i % len(RAMP)]
        series.append(
            SERIES_TEMPLATE
            .replace("COLOR", colour)
            .replace("MARK", MARKS[i % len(MARKS)])
            .replace("FORGET", "")
            .replace("XCOL", xcol)
            .replace("FILTCOL", filtcol)
            .replace("FILTVAL", str(v))
            .replace("TAG", tag)
            .replace("ENTRY", "  \\addlegendentry{$n_{leaf,%s} = %d$}\n"
                              % (sub, v)))

    # Off by default: the naive path is several times slower than every FMM
    # configuration here, so drawing it forces a y range in which the shallow
    # interior minimum -- the entire point of this figure -- flattens to nothing.
    # It belongs on the accuracy-vs-work figure, whose log axes absorb the range.
    naive = ""
    if naive_t is not None:
        naive = ("  \\addplot[black!55, dashed, line width=0.8pt, forget plot]\n"
                 "    coordinates {(%g,%g) (%g,%g)};"
                 % (xs[0], naive_t, xs[-1], naive_t))

    return (PANEL_TEMPLATE
            .replace("AXIS", axis)
            .replace("XTICKS", ",".join(str(x) for x in xs))
            .replace("XTICKLABELS", ",".join(str(x) for x in xs))
            .replace("LEGENDOPT", ", legend to name=" + legend_name)
            .replace("NAIVE", naive)
            .replace("SERIES", "".join(series))
            .replace("LEGEND", ""))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("folder", help="test folder holding the sweep CSV")
    ap.add_argument("--csv", default=None,
                    help="override the CSV path (default: <folder>/leaf_sweep.csv)")
    ap.add_argument("--thesis", default="thesis",
                    help="thesis directory to write into (default: thesis)")
    ap.add_argument("--tag", default=None,
                    help="basename for the generated files (default: leaf_sweep_<folder>)")
    ap.add_argument("--mac", default=None,
                    help="the theta this figure is drawn at; required only if the "
                         "CSV carries more than one")
    ap.add_argument("--order", default=None,
                    help="the multipole order, as above")
    ap.add_argument("--molecule", default=None,
                    help="molecule name for the caption (a replay CSV has no such column)")
    ap.add_argument("--natoms", default=None, help="atom count for the caption, as above")
    fmm_csv.add_machine_argument(ap)
    ap.add_argument("--stat", default="median",
                    choices=sorted(fmm_csv.TIME_STATS),
                    help="how to collapse timing repeats; use min for shared "
                         "cluster nodes, where contention only slows runs down")
    ap.add_argument("--naive", action="store_true",
                    help="draw the naive O(N^2) time as a horizontal line. Off by "
                         "default: it is several times slower than every FMM "
                         "configuration, so it forces a y range that flattens the "
                         "interior minimum this figure exists to show")
    args = ap.parse_args()

    csv_path = args.csv or os.path.join(args.folder, "leaf_sweep.csv")
    if not os.path.exists(csv_path):
        sys.exit("no such CSV: {}".format(csv_path))

    tag = args.tag or "leaf_sweep_" + os.path.basename(os.path.normpath(args.folder))

    rows = fmm_csv.load(csv_path)
    # The error baseline is irrelevant here -- nothing on this figure is an error --
    # so a --no-naive CSV is still perfectly plottable.
    points, info = fmm_csv.aggregate(rows, require_baseline=False,
                                     stat=args.stat)
    if not points:
        sys.exit("no energy_method=2 rows -- nothing to plot")

    points, mac = pick_fixed(points, "mac", args.mac, "mac")
    points, order = pick_fixed(points, "p", args.order, "order")

    srcs = sorted({d["sleaf"] for d in points})
    tgts = sorted({d["tleaf"] for d in points})
    if len(srcs) < 2 and len(tgts) < 2:
        sys.exit("only one leaf configuration in the CSV -- nothing to sweep")

    best = min(points, key=lambda d: d["time"])
    naive_t = info["naive_t"] if args.naive else None

    times = [d["time"] for d in points]
    lo, hi = min(times), max(times)
    if naive_t is not None:
        lo, hi = min(lo, naive_t), max(hi, naive_t)
    pad = 0.08 * (hi - lo) if hi > lo else 0.1 * hi
    ylo, yhi = max(0.0, lo - pad), hi + pad

    data_dir = os.path.join(args.thesis, "figures", "data")
    os.makedirs(data_dir, exist_ok=True)
    dat = os.path.join(data_dir, tag + ".dat")
    reftex = os.path.join(data_dir, tag + "_ref.tex")
    fig = os.path.join(args.thesis, "figures", tag + ".tex")

    with open(dat, "w") as fh:
        fh.write("sleaf tleaf time t_build t_pol t_ionic\n")
        for d in sorted(points, key=lambda d: (d["sleaf"], d["tleaf"])):
            fh.write("{} {} {:.6g} {} {} {}\n".format(
                d["sleaf"], d["tleaf"], d["time"],
                *["{:.6g}".format(d[k]) if d[k] is not None else "nan"
                  for k in ("t_build", "t_pol", "t_ionic")]))

    molecule = args.molecule or os.path.splitext(info["molecule"])[0] or "?"
    nrep = int(statistics.median(d["n"] for d in points))
    if naive_t is not None:
        naive_note = (" The dashed line is the naive $\\mathcal{O}(N^2)$ GPU path at "
                      "%.3g\\,s." % naive_t)
    elif info["naive_t"] is not None:
        naive_note = (" Every configuration shown beats the naive $\\mathcal{O}(N^2)$ GPU "
                      "path, which takes %.3g\\,s and is off the scale of this "
                      "figure." % info["naive_t"])
    else:
        naive_note = " The naive path was not measured in this sweep."

    ref_buf = [
        "% generated by scripts/plot_leaf_sweep.py -- do not edit\n",
        "\\def\\leafMolecule{%s}\n" % molecule,
        "\\def\\leafNatoms{%s}\n" % (args.natoms or info["natoms"] or "?"),
        "\\def\\leafMac{%g}\n" % mac,
        "\\def\\leafOrder{%d}\n" % order,
        "\\def\\leafRepeats{%d}\n" % nrep,
        "\\def\\leafBest{$%d/%d$}\n" % (best["sleaf"], best["tleaf"]),
        "\\def\\leafNaiveNote{%s}\n" % naive_note,
        "\\def\\leafMachine{%s}\n"
        % fmm_csv.machine_note(args.machine, info["ranks"]),
    ]
    with open(reftex, "w") as fh:
        fh.write(localise("".join(ref_buf), tag))

    colordefs = "\n".join(
        "\\definecolor{%s}{HTML}{%s}" % (n, h)
        for n, h in RAMP[:max(len(srcs), len(tgts))])

    panels = (build_panel("src", "sleaf", "tleaf", tgts, points, tag,
                          "leafsweeplegendsrcSFX", naive_t)
              + build_panel("tgt", "tleaf", "sleaf", srcs, points, tag,
                            "leafsweeplegendtgtSFX", naive_t))

    with open(fig, "w") as fh:
        fh.write(localise(FIGURE_TEMPLATE
                 .replace("COLORDEFS", colordefs)
                 .replace("PANELS", panels)
                 .replace("YMIN", "{:.6g}".format(ylo))
                 .replace("YMAX", "{:.6g}".format(yhi))
                 # Four is what fits the text width: the entries are wide ("n_leaf,tgt = 2048")
                 # and six of them overflow the margin. Six entries then wrap to two rows.
                 .replace("LEGCOLS", str(min(len(tgts), 4))), tag))

    print("configurations : {}  ({} repeats each)".format(len(points), nrep))
    print("held fixed     : theta = {:g}, p = {}".format(mac, order))
    print("source leaves  : {}".format(", ".join(str(v) for v in srcs)))
    print("target leaves  : {}".format(", ".join(str(v) for v in tgts)))
    if info["naive_t"] is not None:
        print("naive O(N^2)   : {:.4f} s".format(info["naive_t"]))
    print()
    print("wrote {}".format(dat))
    print("      {}".format(reftex))
    print("      {}".format(fig))
    print()
    print("fastest        : src {} / tgt {}  at {:.4f} s".format(
        best["sleaf"], best["tleaf"], best["time"]))

    # An optimum on the boundary is not an optimum -- it is the edge of the sweep.
    edge = []
    if len(srcs) > 1 and best["sleaf"] in (srcs[0], srcs[-1]):
        edge.append("source ({})".format(best["sleaf"]))
    if len(tgts) > 1 and best["tleaf"] in (tgts[0], tgts[-1]):
        edge.append("target ({})".format(best["tleaf"]))
    if edge:
        print("WARNING: best config sits on the swept boundary in {} -- "
              "widen the grid before calling it an optimum".format(" and ".join(edge)))
    else:
        print("both axes interior -- the optimum is bracketed")

    print()
    print("per source leaf (best target, time):")
    for s in srcs:
        row = min((d for d in points if d["sleaf"] == s), key=lambda d: d["time"])
        print("  src {:>5} -> tgt {:>5}  {:.4f} s".format(s, row["tleaf"], row["time"]))


if __name__ == "__main__":
    main()