#!/usr/bin/env python3
r"""
Show that the optimal SOURCE leaf size moves with p, and only weakly with theta.

This is the figure behind the correction to the "both leaf sizes should be equal"
reading. The two trees are not symmetric knobs: the source leaf bounds the box
radius the MAC tests against (near-field P2P work) while the target leaf sets the
target box count (M2L pair count). Raising p makes each M2L dearer without
touching the tree geometry at all -- fmm_build_atom_tree uses p only for
comp_of(p) -- so the balance point moves toward fewer, larger source boxes. That
prediction is what the left panel tests.

    left panel   x = source leaf, one line per multipole order p
                 the minimum of each line walks RIGHT as p grows
    right panel  x = source leaf, one line per theta, each normalized to its own
                 minimum, so the shape can be compared across a 4x range in
                 absolute time. Theta changes how SHARP the optimum is; it barely
                 moves WHERE it is.

Both panels hold the target leaf fixed -- with both leaf axes free the minimum
runs along s*t ~ const and neither panel would show a clean interior optimum.

Takes several CSVs per panel because the p range was measured in two runs
(leaf_vs_p_low.csv for p=6..8, leaf_vs_p.csv for p=9..11); they are concatenated.

Writes, relative to the thesis directory:
    figures/data/<tag>_p.dat        one row per (p, source leaf)
    figures/data/<tag>_theta.dat    one row per (theta, source leaf)
    figures/data/<tag>_ref.tex      caption values as macros
    figures/<tag>.tex               the figure
    figures/<tag>_table.tex         the argmin table, \input-able separately

Sibling of plot_leaf_sweep.py (which sweeps the two leaf axes against each other
at fixed p and theta); this one holds the target leaf fixed and sweeps p and
theta instead. Shares the CSV layer, fmm_csv.py.
"""

import argparse
import os
import re
import statistics
import sys

import fmm_csv

# Same ramp as plot_leaf_sweep.py, for the same reason: ordered by lightness so
# the lines stay separable in greyscale and under the common CVD types.
RAMP = [
    ("shiftA", "1B3A6B"),
    ("shiftB", "1F77B4"),
    ("shiftC", "17A398"),
    ("shiftD", "7EA83D"),
    ("shiftE", "E8A33D"),
    ("shiftF", "C1272D"),
]
MARKS = ["*", "square*", "triangle*", "diamond*", "pentagon*", "oplus*"]

SHIFT_MACROS = ["shiftMolecule", "shiftNatoms", "shiftMac", "shiftOrder",
                "shiftTgt", "shiftRepeats", "shiftMachine"]


def localise(text, tag):
    r"""Make macros, labels and legend names unique to this figure.

    \def is global and more than one of these figures can appear in one
    document, so shared names would have every caption read whichever figure was
    typeset last. Same treatment as plot_leaf_sweep.py.
    """
    sfx = "".join(c for c in tag if c.isalpha())
    # (?![A-Za-z]) is load-bearing: a LaTeX control sequence ends at the
    # first non-letter, so a plain replace of \\leafMac also rewrites the
    # \\leafMachine that starts with it -- which it did, silently producing
    # \\leafMacleafsweepvybhine and an undefined macro in the caption.
    for name in SHIFT_MACROS:
        text = re.sub(r"\\" + name + r"(?![A-Za-z])",
                      "\\\\" + name + sfx, text)
    return text.replace("SFX", sfx).replace("TAG", tag)


def load_points(paths, stat):
    """Aggregate several replay CSVs into one point list."""
    rows = []
    for p in paths:
        if not os.path.exists(p):
            sys.exit("no such CSV: {}".format(p))
        rows.extend(fmm_csv.load(p))
    if not rows:
        sys.exit("no usable rows in {}".format(", ".join(paths)))
    points, info = fmm_csv.aggregate(rows, require_baseline=False, stat=stat)
    if not points:
        sys.exit("no energy_method=2 rows in {}".format(", ".join(paths)))
    return points, info


def hold_fixed(points, key, wanted, label):
    """Reduce to one value of an axis this figure holds fixed."""
    present = sorted({d[key] for d in points})
    if wanted is not None:
        chosen = type(present[0])(wanted)
        if chosen not in present:
            sys.exit("no rows with {} = {} (have {})".format(
                label, wanted, ", ".join("{:g}".format(v) for v in present)))
        return [d for d in points if d[key] == chosen], chosen
    if len(present) > 1:
        sys.exit("CSV carries {} values of {} ({}) -- this figure holds it "
                 "fixed, so pass --{} to choose".format(
                     len(present), label,
                     ", ".join("{:g}".format(v) for v in present), label))
    return points, present[0]


FIGURE_TEMPLATE = r"""% ------------------------------------------------------------------------
%  Where the source-leaf optimum sits, as a function of p and of theta.
%  Generated by scripts/plot_leaf_optimum_shift.py -- regenerate rather than edit.
%  Include with \input{figures/TAG}
%  Needs \usepackage{pgfplots} in the preamble.
% ------------------------------------------------------------------------
\input{figures/data/TAG_ref}

\pgfplotsset{compat=1.16}
\usepgfplotslibrary{groupplots}

\pgfplotsset{
  discard if not/.style n args={2}{
    x filter/.code={%
      \edef\tempa{\thisrow{#1}}\edef\tempb{#2}%
      \ifx\tempa\tempb\else\def\pgfmathresult{inf}\fi
    }
  }
}

COLORDEFS

\begin{figure}[!htb]
\centering
\begin{tikzpicture}
\begin{groupplot}[
    group style={
      group size=2 by 1,
      horizontal sep=1.5cm,
    },
    width=7.4cm, height=5.6cm,
    xmode=log, log basis x=2,
    xlabel={$n_{leaf,src}$},
    xtick={XTICKS}, xticklabels={XTICKS},
    xlabel style={font=\footnotesize},
    ylabel style={font=\footnotesize},
    tick label style={font=\scriptsize},
    title style={font=\footnotesize, yshift=-0.4ex},
    grid=both,
    major grid style={black!12},
    minor grid style={black!5},
    minor tick num=0,
    legend style={draw=none, font=\footnotesize, column sep=0.6em},
]
PANELS
\end{groupplot}
\end{tikzpicture}

\vspace{0.4ex}
\ref{shiftlegendpSFX}

\vspace{0.2ex}
\ref{shiftlegendthetaSFX}

\caption[Source-leaf sweeps against $P$ and $\theta$]{\textbf{The source leaf
    size on \shiftMolecule{} (\shiftNatoms{} atoms), swept against $P$ and
    against $\theta$, with $n_{leaf,tgt} = \shiftTgt{}$.} \shiftRepeats{}-repeat
    medians; open circles mark each line's minimum. \emph{Left:} one line per
    multipole order, at $\theta = \shiftMac{}$. \emph{Right:} one line per
    $\theta$, at $P = \shiftOrder{}$, each normalized to its own minimum so the
    shapes stay comparable.\shiftMachine}
\label{fig:TAG}
\end{figure}
"""

PANEL_TEMPLATE = r"""
\nextgroupplot[ylabel={YLABEL}, ymin=YMIN, ymax=YMAX, legend columns=LEGCOLS, legend to name=LEGNAME]
SERIESMINIMA"""

SERIES_TEMPLATE = r"""  \addplot[color=COLOR, mark=MARK, mark size=1.3pt, line width=0.9pt]
    table[x=sleaf, y=YCOL, discard if not={FILTCOL}{FILTVAL}] {figures/data/DATFILE.dat};
  \addlegendentry{ENTRY}
"""

# One overlay per panel rather than per series: it is the WALK of the minima that
# the figure is about, and a single marker style makes that read as one object.
MINIMA_TEMPLATE = r"""  \addplot[only marks, mark=o, mark size=3.6pt, line width=0.9pt,
           color=black!75, forget plot] coordinates {COORDS};
"""


def build_panel(series, ylabel, ycol, filtcol, datfile, legname, ylo, yhi,
                minima, legcols):
    body = []
    for i, (value, entry) in enumerate(series):
        colour, _ = RAMP[i % len(RAMP)]
        body.append(SERIES_TEMPLATE
                    .replace("COLOR", colour)
                    .replace("MARK", MARKS[i % len(MARKS)])
                    .replace("YCOL", ycol)
                    .replace("FILTCOL", filtcol)
                    .replace("FILTVAL", str(value))
                    .replace("DATFILE", datfile)
                    .replace("ENTRY", entry))
    coords = " ".join("({:g},{:.6g})".format(x, y) for x, y in minima)
    return (PANEL_TEMPLATE
            .replace("YLABEL", ylabel)
            .replace("YMIN", "{:.6g}".format(ylo))
            .replace("YMAX", "{:.6g}".format(yhi))
            .replace("LEGCOLS", str(legcols))
            .replace("LEGNAME", legname)
            .replace("SERIES", "".join(body))
            .replace("MINIMA", MINIMA_TEMPLATE.replace("COORDS", coords)))


TABLE_TEMPLATE = r"""% ------------------------------------------------------------------------
%  Generated by scripts/plot_leaf_optimum_shift.py -- regenerate rather than edit.
%  Include with \input{figures/TAG_table}
%  Needs \usepackage{booktabs}.
% ------------------------------------------------------------------------
\begin{table}[!htb]
\centering
\footnotesize
\caption[Fastest source leaf against $P$ and $\theta$]{\textbf{The fastest source
    leaf size on \shiftMolecule{}, target leaf \shiftTgt{}.} Left block: against
    $P$, at $\theta = \shiftMac{}$. Right block: against $\theta$, at
    $P = \shiftOrder{}$. \emph{margin} is how much slower the runner-up
    is.\shiftMachine}
\label{tab:TAG}
\begin{tabular}{rrrr@{\hskip 2em}rrrr}
\toprule
\multicolumn{4}{c}{at $\theta = \shiftMac{}$} & \multicolumn{4}{c}{at $P = \shiftOrder{}$} \\
\cmidrule(r){1-4}\cmidrule(l){5-8}
$P$ & best $n_{leaf,src}$ & time [s] & margin & $\theta$ & best $n_{leaf,src}$ & time [s] & margin \\
\midrule
ROWS
\bottomrule
\end{tabular}
\end{table}
"""


def argmin_rows(points, key):
    """(key value, best source leaf, its time, runner-up margin) per key value."""
    out = []
    for value in sorted({d[key] for d in points}):
        line = sorted((d for d in points if d[key] == value),
                      key=lambda d: d["time"])
        best = line[0]
        margin = (line[1]["time"] / best["time"] - 1.0) if len(line) > 1 else None
        out.append((value, best["sleaf"], best["time"], margin))
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--p-csv", nargs="+", required=True,
                    help="replay CSV(s) sweeping p at fixed theta and target leaf")
    ap.add_argument("--theta-csv", nargs="+", required=True,
                    help="replay CSV(s) sweeping theta at fixed target leaf")
    ap.add_argument("--thesis", default="thesis",
                    help="thesis directory to write into (default: thesis)")
    ap.add_argument("--tag", default="leaf_optimum_shift",
                    help="basename for the generated files")
    ap.add_argument("--mac", default=None,
                    help="the theta the LEFT panel is drawn at (required only if "
                         "the p CSVs carry more than one)")
    ap.add_argument("--order", default=None,
                    help="the p the RIGHT panel is drawn at (required only if the "
                         "theta CSVs carry more than one)")
    ap.add_argument("--tgt", default=None,
                    help="the target leaf both panels hold fixed")
    ap.add_argument("--molecule", default=None,
                    help="molecule name for the caption (a replay CSV has no such column)")
    ap.add_argument("--natoms", default=None, help="atom count for the caption")
    fmm_csv.add_machine_argument(ap)
    ap.add_argument("--stat", default="median",
                    choices=sorted(fmm_csv.TIME_STATS),
                    help="how to collapse timing repeats; use min for shared "
                         "cluster nodes, where contention only slows runs down")
    args = ap.parse_args()

    p_points, p_info = load_points(args.p_csv, args.stat)
    t_points, _ = load_points(args.theta_csv, args.stat)

    p_points, _ = hold_fixed(p_points, "tleaf", args.tgt, "tgt")
    p_points, mac = hold_fixed(p_points, "mac", args.mac, "mac")
    t_points, _ = hold_fixed(t_points, "tleaf", args.tgt, "tgt")
    t_points, order = hold_fixed(t_points, "p", args.order, "order")

    tgt = p_points[0]["tleaf"]
    if t_points[0]["tleaf"] != tgt:
        sys.exit("the two panels hold different target leaves ({} vs {}) -- "
                 "pass --tgt".format(tgt, t_points[0]["tleaf"]))

    orders = sorted({d["p"] for d in p_points})
    macs = sorted({d["mac"] for d in t_points})
    if len(orders) < 2:
        sys.exit("only one p in the p CSVs -- nothing to show")

    # Normalise each theta line to its own minimum: theta moves absolute time by
    # ~4x over this range, which would otherwise stack the curves so far apart
    # that their SHAPES -- the actual subject of the panel -- cannot be compared.
    for m in macs:
        line = [d for d in t_points if d["mac"] == m]
        lo = min(d["time"] for d in line)
        for d in line:
            d["tnorm"] = d["time"] / lo

    srcs = sorted({d["sleaf"] for d in p_points} | {d["sleaf"] for d in t_points})

    data_dir = os.path.join(args.thesis, "figures", "data")
    os.makedirs(data_dir, exist_ok=True)
    p_dat = os.path.join(data_dir, args.tag + "_p.dat")
    t_dat = os.path.join(data_dir, args.tag + "_theta.dat")
    reftex = os.path.join(data_dir, args.tag + "_ref.tex")
    fig = os.path.join(args.thesis, "figures", args.tag + ".tex")
    tab = os.path.join(args.thesis, "figures", args.tag + "_table.tex")

    with open(p_dat, "w") as fh:
        fh.write("sleaf p time\n")
        for d in sorted(p_points, key=lambda d: (d["p"], d["sleaf"])):
            fh.write("{} {} {:.6g}\n".format(d["sleaf"], d["p"], d["time"]))

    # mac10 rather than mac: pgfplots' discard-if-not compares the column text to
    # the filter text, and "0.3" from the file would have to match "0.3" written
    # into the style by hand. An integer key removes the float-formatting question.
    with open(t_dat, "w") as fh:
        fh.write("sleaf mac10 time tnorm\n")
        for d in sorted(t_points, key=lambda d: (d["mac"], d["sleaf"])):
            fh.write("{} {} {:.6g} {:.6g}\n".format(
                d["sleaf"], int(round(d["mac"] * 10)), d["time"], d["tnorm"]))

    p_rows = argmin_rows(p_points, "p")
    t_rows = argmin_rows(t_points, "mac")

    p_minima = [(sleaf, time) for _, sleaf, time, _ in p_rows]
    t_minima = [(sleaf, 1.0) for _, sleaf, _, _ in t_rows]

    times = [d["time"] for d in p_points]
    pad = 0.08 * (max(times) - min(times))
    norms = [d["tnorm"] for d in t_points]
    npad = 0.08 * (max(norms) - min(norms))

    panels = (
        build_panel([(p, "$P = %d$" % p) for p in orders],
                    "energy calculation [s]", "time", "p", args.tag + "_p",
                    "shiftlegendpSFX", min(times) - pad, max(times) + pad,
                    p_minima, min(len(orders), 6))
        + build_panel([(int(round(m * 10)), "$\\theta = %g$" % m) for m in macs],
                      "time / line minimum", "tnorm", "mac10",
                      args.tag + "_theta", "shiftlegendthetaSFX",
                      min(norms) - npad, max(norms) + npad,
                      t_minima, min(len(macs), 4))
    )

    # Printed to the console, deliberately NOT emitted as caption macros. The
    # caption states what the figure shows; what the figure MEANS belongs in the
    # body text, which is the author's to write.
    walk = ", ".join(str(sleaf) for _, sleaf, _, _ in p_rows)
    moved = len({s for _, s, _, _ in t_rows})

    molecule = args.molecule or os.path.splitext(p_info["molecule"])[0] or "?"
    nrep = int(statistics.median(d["n"] for d in p_points))

    ref_buf = [
        "% generated by scripts/plot_leaf_optimum_shift.py -- do not edit\n",
        "\\def\\shiftMolecule{%s}\n" % molecule,
        "\\def\\shiftNatoms{%s}\n" % (args.natoms or p_info["natoms"] or "?"),
        "\\def\\shiftMac{%g}\n" % mac,
        "\\def\\shiftOrder{%d}\n" % order,
        "\\def\\shiftTgt{%d}\n" % tgt,
        "\\def\\shiftRepeats{%d}\n" % nrep,
        "\\def\\shiftMachine{%s}\n"
        % fmm_csv.machine_note(args.machine, p_info["ranks"]),
    ]
    with open(reftex, "w") as fh:
        fh.write(localise("".join(ref_buf), args.tag))

    colordefs = "\n".join("\\definecolor{%s}{HTML}{%s}" % (n, h)
                          for n, h in RAMP[:max(len(orders), len(macs))])

    with open(fig, "w") as fh:
        fh.write(localise(FIGURE_TEMPLATE
                          .replace("COLORDEFS", colordefs)
                          .replace("PANELS", panels)
                          .replace("XTICKS", ",".join(str(s) for s in srcs)),
                          args.tag))

    def fmt(margin):
        return "--" if margin is None else "{:.1f}\\%".format(100.0 * margin)

    body = []
    for i in range(max(len(p_rows), len(t_rows))):
        left = ("{} & {} & {:.3f} & {}".format(p_rows[i][0], p_rows[i][1],
                                               p_rows[i][2], fmt(p_rows[i][3]))
                if i < len(p_rows) else " & & & ")
        right = ("{:g} & {} & {:.3f} & {}".format(t_rows[i][0], t_rows[i][1],
                                                  t_rows[i][2], fmt(t_rows[i][3]))
                 if i < len(t_rows) else " & & & ")
        body.append(left + " & " + right + " \\\\\n")
    with open(tab, "w") as fh:
        fh.write(localise(TABLE_TEMPLATE.replace("ROWS", "".join(body)), args.tag))

    print("target leaf held at : {}".format(tgt))
    print("left  panel : theta = {:g}, p = {}".format(
        mac, ", ".join(str(o) for o in orders)))
    print("right panel : p = {}, theta = {}".format(
        order, ", ".join("{:g}".format(m) for m in macs)))
    print()
    print("walk of the optimum          : {}  (p = {} to {}{})".format(
        walk, p_rows[0][0], p_rows[-1][0],
        "; unchanged across theta" if moved == 1 else "; theta moves it too"))
    print("best source leaf vs p        (theta = {:g})".format(mac))
    for p, sleaf, time, margin in p_rows:
        print("   p={:<3} src {:<4} {:.3f}s   runner-up +{}".format(
            p, sleaf, time, fmt(margin).replace("\\", "")))
    print("best source leaf vs theta    (p = {})".format(order))
    for m, sleaf, time, margin in t_rows:
        print("   theta={:<5g} src {:<4} {:.3f}s   runner-up +{}".format(
            m, sleaf, time, fmt(margin).replace("\\", "")))
    print()
    print("wrote {}".format(p_dat))
    print("      {}".format(t_dat))
    print("      {}".format(reftex))
    print("      {}".format(fig))
    print("      {}".format(tab))


if __name__ == "__main__":
    sys.exit(main())
