#!/usr/bin/env python3
r"""
Separate the two things that move the leaf optimum: the GPU and the rank count.

Every cluster-vs-local comparison so far changed both at once (4 ranks on an
RTX 3080 against 16 on an A100), so neither effect could be attributed. With a
4-rank run on the A100 as the pivot, the two are separable:

    local 4r  ->  A100 4r      only the GPU changed
    A100 4r   ->  A100 16r     only the rank count changed

and the two trees respond differently, which is a structural property rather
than a coincidence: the SOURCE tree is built from the atoms, which every rank
holds a full copy of, so the rank count cannot reach it. The TARGET tree is
built from this rank's share of the surface points, so the rank count sets its
size directly.

    left panel   x = source leaf at a fixed target leaf
    right panel  x = target leaf at a fixed source leaf

Each line is normalised to its own minimum, because the three configurations
differ by up to 3.5x in absolute time and the subject here is the SHAPE -- where
each curve bottoms out, not how high it sits.

Writes, relative to the thesis directory:
    figures/data/<tag>_src.dat    one row per (series, source leaf)
    figures/data/<tag>_tgt.dat    one row per (series, target leaf)
    figures/data/<tag>_ref.tex    caption values as macros
    figures/<tag>.tex             the figure
    figures/<tag>_table.tex       the grid-wide optimum of each series

Sibling of plot_leaf_optimum_shift.py, which holds the platform fixed and sweeps
p and theta; this one holds p and theta fixed and varies the platform.
"""

import argparse
import os
import re
import statistics
import sys

import fmm_csv

# Three series is the design point (local 4r / A100 4r / A100 16r). The ramp
# runs cool-to-warm so it survives greyscale, and the first two -- the pair that
# differs only in GPU -- are the two blues, so the eye groups them.
RAMP = [
    ("platA", "1B3A6B"),
    ("platB", "1F77B4"),
    ("platC", "D95F02"),
    ("platD", "7EA83D"),
]
MARKS = ["*", "square*", "triangle*", "diamond*"]

PLAT_MACROS = ["platMolecule", "platNatoms", "platMac", "platOrder",
               "platFixedTgt", "platFixedSrc", "platRepeats", "platMachine"]


def localise(text, tag):
    r"""Suffix this figure's macros and labels so several can coexist."""
    sfx = "".join(c for c in tag if c.isalpha())
    # (?![A-Za-z]) because a control sequence ends at the first non-letter:
    # without it \platMac would also rewrite the \platMachine that starts with it.
    for name in PLAT_MACROS:
        text = re.sub(r"\\" + name + r"(?![A-Za-z])", "\\\\" + name + sfx, text)
    return text.replace("SFX", sfx).replace("TAG", tag)


def load_series(spec, stat):
    """"LABEL=path" -> (label, {(sleaf, tleaf): time}, info)."""
    if "=" not in spec:
        sys.exit("series must be LABEL=path/to/leaf_sweep.csv, got %r" % spec)
    label, path = spec.split("=", 1)
    if not os.path.exists(path):
        sys.exit("no such CSV: %s" % path)
    rows = fmm_csv.load(path)
    points, info = fmm_csv.aggregate(rows, require_baseline=False, stat=stat)
    if not points:
        sys.exit("no energy_method=2 rows in %s" % path)
    grid = {(d["sleaf"], d["tleaf"]): d for d in points}

    # Widest repeat-to-repeat variation anywhere in this grid. The table reports
    # it so a 0.3% runner-up margin can be read against the noise it sits in.
    by_cfg = {}
    for r in rows:
        if r.get("energy_method") != "2":
            continue
        k = (r["fmm_mac"], r["fmm_multipole_order"], r["fmm_leaf_size"],
             r.get("fmm_target_leaf_size"))
        by_cfg.setdefault(k, []).append(float(r["t_energy"]))
    spreads = [(max(v) - min(v)) / statistics.median(v)
               for v in by_cfg.values() if len(v) > 1]
    info["spread"] = max(spreads) if spreads else None
    return label.strip(), grid, info


def profile(grid, axis, fixed_other):
    """Normalised slice through the grid: [(x, time/min)] along `axis`."""
    if axis == "src":
        pts = {s: d for (s, t), d in grid.items() if t == fixed_other}
    else:
        pts = {t: d for (s, t), d in grid.items() if s == fixed_other}
    if not pts:
        return []
    lo = min(d["time"] for d in pts.values())
    return sorted((x, d["time"] / lo, d["time"]) for x, d in pts.items())


FIGURE_TEMPLATE = r"""% ------------------------------------------------------------------------
%  Which platform change moves which leaf axis.
%  Generated by scripts/plot_platform_shift.py -- regenerate rather than edit.
%  Include with \input{figures/TAG}
%  Needs \usepackage{pgfplots} in the preamble.
% ------------------------------------------------------------------------
\input{figures/data/TAG_ref}

\pgfplotsset{compat=1.16}
\usepgfplotslibrary{groupplots}

\pgfplotsset{
  discard if not/.style n args={2}{
    x filter/.code={%
      \edef\tempa{\thisrow{#1}}\edef\tempb{#2}%
      \ifx\tempa\tempb\else\def\pgfmathresult{inf}\fi
    }
  }
}

COLORDEFS

\begin{figure}[!htb]
\centering
\begin{tikzpicture}
\begin{groupplot}[
    group style={
      group size=2 by 1,
      horizontal sep=1.5cm,
    },
    width=7.4cm, height=5.6cm,
    xmode=log, log basis x=2,
    ylabel={time / line minimum},
    xlabel style={font=\footnotesize},
    ylabel style={font=\footnotesize},
    tick label style={font=\scriptsize},
    title style={font=\footnotesize, yshift=-0.4ex},
    grid=both,
    major grid style={black!12},
    minor grid style={black!5},
    minor tick num=0,
    legend style={draw=none, font=\footnotesize, column sep=0.6em},
]
PANELS
\end{groupplot}
\end{tikzpicture}

\vspace{0.4ex}
\ref{platlegendsrcSFX}

\vspace{0.2ex}
\ref{platlegendtgtSFX}

\caption[Which platform change moves which leaf axis]{\textbf{The two leaf axes
    on \platMolecule{} (\platNatoms{} atoms) under a change of GPU and a change
    of rank count, at $\theta = \platMac{}$ and $P = \platOrder{}$.} Each line is
    the \platRepeats{}-repeat median normalised to its own minimum, so the three
    configurations can be compared by shape across a threefold range in absolute
    time; open circles mark the minima. \emph{Left:} the source leaf axis.
    \emph{Right:} the target leaf axis. Each line is sliced through its own
    configuration's grid-wide optimum, given in the legend, rather than through a
    single shared value: the two knobs trade against each other, so a slice taken
    at one platform's optimum falls on another's flat region. The first two
    series differ only in the GPU, the last two only in the rank
    count.\platMachine}
\label{fig:TAG}
\end{figure}
"""

PANEL_TEMPLATE = r"""
\nextgroupplot[xlabel={$n_{leaf,AXIS}$}, xtick={XTICKS}, xticklabels={XTICKS}, ymin=YMIN, ymax=YMAX, legend columns=LEGCOLS, legend to name=LEGNAME]
SERIESMINIMA"""

SERIES_TEMPLATE = r"""  \addplot[color=COLOR, mark=MARK, mark size=1.3pt, line width=0.9pt]
    table[x=x, y=tnorm, discard if not={sid}{SID}] {figures/data/DATFILE.dat};
ENTRY"""

MINIMA_TEMPLATE = r"""  \addplot[only marks, mark=o, mark size=3.6pt, line width=0.9pt,
           color=black!75, forget plot] coordinates {COORDS};
"""


def build_panel(axis, series, datfile, xs, legname, legend, ylo, yhi, minima):
    body = []
    for sid, (label, _) in enumerate(series):
        colour, _ = RAMP[sid % len(RAMP)]
        body.append(SERIES_TEMPLATE
                    .replace("COLOR", colour)
                    .replace("MARK", MARKS[sid % len(MARKS)])
                    .replace("SID", str(sid))
                    .replace("DATFILE", datfile)
                    .replace("ENTRY",
                             "  \\addlegendentry{%s}\n" % label if legend else ""))
    coords = " ".join("({:g},{:.6g})".format(x, y) for x, y in minima)
    return (PANEL_TEMPLATE
            .replace("AXIS", axis)
            .replace("XTICKS", ",".join(str(x) for x in xs))
            .replace("YMIN", "{:.6g}".format(ylo))
            .replace("YMAX", "{:.6g}".format(yhi))
            .replace("LEGCOLS", str(min(len(series), 3)))
            .replace("LEGNAME", legname if legend else "platlegendunusedSFX")
            .replace("SERIES", "".join(body))
            .replace("MINIMA", MINIMA_TEMPLATE.replace("COORDS", coords)))


TABLE_TEMPLATE = r"""% ------------------------------------------------------------------------
%  Generated by scripts/plot_platform_shift.py -- regenerate rather than edit.
%  Include with \input{figures/TAG_table}
%  Needs \usepackage{booktabs}.
% ------------------------------------------------------------------------
\begin{table}[!htb]
\centering
\footnotesize
\caption[Leaf optimum by platform]{\textbf{The fastest leaf pair on
    \platMolecule{} over the whole $4 \times 6$ grid, for each platform, at
    $\theta = \platMac{}$ and $P = \platOrder{}$.} \emph{runner-up} is how much
    slower the second-best pair is, and \emph{spread} the widest
    repeat-to-repeat variation in that series.\platMachine}
\label{tab:TAG}
\begin{tabular}{lrrrrr}
\toprule
platform & $n_{leaf,src}$ & $n_{leaf,tgt}$ & time [s] & runner-up & spread \\
\midrule
ROWS
\bottomrule
\end{tabular}
\end{table}
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("series", nargs="+",
                    help="LABEL=path/to/leaf_sweep.csv, in the order they should "
                         "be drawn; the design expects local-4r, A100-4r, A100-16r")
    ap.add_argument("--thesis", default="thesis")
    ap.add_argument("--tag", default="platform_shift")
    ap.add_argument("--fixed-tgt", type=int, default=None,
                    help="hold ALL series' left panel at this target leaf. "
                         "Default is to slice each series through its OWN "
                         "optimum -- a shared slice is not neutral here, because "
                         "the two knobs trade along s*t and a slice taken at one "
                         "platform's optimum lands on another's flat region")
    ap.add_argument("--fixed-src", type=int, default=None,
                    help="hold ALL series' right panel at this source leaf, as above")
    ap.add_argument("--molecule", default=None)
    ap.add_argument("--natoms", default=None)
    fmm_csv.add_machine_argument(ap)
    ap.add_argument("--stat", default="median",
                    choices=sorted(fmm_csv.TIME_STATS))
    args = ap.parse_args()

    loaded = [load_series(s, args.stat) for s in args.series]
    if len(loaded) < 2:
        sys.exit("need at least two series to compare")

    macs = {d["mac"] for _, g, _ in loaded for d in g.values()}
    orders = {d["p"] for _, g, _ in loaded for d in g.values()}
    if len(macs) != 1 or len(orders) != 1:
        sys.exit("the series disagree on theta (%s) or p (%s) -- this figure "
                 "holds both fixed" % (sorted(macs), sorted(orders)))
    mac, order = macs.pop(), orders.pop()

    def best_of(grid):
        return min(grid, key=lambda k: grid[k]["time"])

    # Per-series slice unless told otherwise: each curve is the profile through
    # that platform's OWN grid optimum, which is the operating point anyone would
    # actually run it at. A single shared slice reproduces whichever platform it
    # was taken from and reads as noise on the others.
    fixed = [(args.fixed_tgt or best_of(g)[1], args.fixed_src or best_of(g)[0])
             for _, g, _ in loaded]

    src_prof = [("%s (tgt %d)" % (lab, fx[0]), profile(g, "src", fx[0]))
                for (lab, g, _), fx in zip(loaded, fixed)]
    tgt_prof = [("%s (src %d)" % (lab, fx[1]), profile(g, "tgt", fx[1]))
                for (lab, g, _), fx in zip(loaded, fixed)]
    fixed_tgt = fixed[0][0]
    fixed_src = fixed[0][1]
    for name, prof in (("source", src_prof), ("target", tgt_prof)):
        for lab, rows in prof:
            if not rows:
                sys.exit("series %r has no %s-axis rows at the fixed value" %
                         (lab, name))

    data_dir = os.path.join(args.thesis, "figures", "data")
    os.makedirs(data_dir, exist_ok=True)
    src_dat = os.path.join(data_dir, args.tag + "_src.dat")
    tgt_dat = os.path.join(data_dir, args.tag + "_tgt.dat")
    reftex = os.path.join(data_dir, args.tag + "_ref.tex")
    fig = os.path.join(args.thesis, "figures", args.tag + ".tex")
    tab = os.path.join(args.thesis, "figures", args.tag + "_table.tex")

    for path, prof in ((src_dat, src_prof), (tgt_dat, tgt_prof)):
        with open(path, "w") as fh:
            fh.write("sid x tnorm time\n")
            for sid, (_, rows) in enumerate(prof):
                for x, tnorm, t in rows:
                    fh.write("{} {} {:.6g} {:.6g}\n".format(sid, x, tnorm, t))

    src_xs = sorted({x for _, rows in src_prof for x, _, _ in rows})
    tgt_xs = sorted({x for _, rows in tgt_prof for x, _, _ in rows})
    src_min = [min(rows, key=lambda r: r[1])[:2] for _, rows in src_prof]
    tgt_min = [min(rows, key=lambda r: r[1])[:2] for _, rows in tgt_prof]

    def span(prof):
        v = [t for _, rows in prof for _, t, _ in rows]
        pad = 0.08 * (max(v) - min(v))
        return min(v) - pad, max(v) + pad

    slo, shi = span(src_prof)
    tlo, thi = span(tgt_prof)

    # Each panel gets its OWN legend: the entries carry the value the other axis
    # is held at, and that differs between the panels, so one shared legend would
    # label the right-hand panel with the left-hand panel's slices.
    panels = (build_panel("src", src_prof, args.tag + "_src", src_xs,
                          "platlegendsrcSFX", True, slo, shi, src_min)
              + build_panel("tgt", tgt_prof, args.tag + "_tgt", tgt_xs,
                            "platlegendtgtSFX", True, tlo, thi, tgt_min))

    molecule = args.molecule or os.path.splitext(loaded[0][2]["molecule"])[0] or "?"
    nrep = int(statistics.median(d["n"] for _, g, _ in loaded for d in g.values()))
    ranks = {info["ranks"] for _, _, info in loaded}

    ref_buf = [
        "% generated by scripts/plot_platform_shift.py -- do not edit\n",
        "\\def\\platMolecule{%s}\n" % molecule,
        "\\def\\platNatoms{%s}\n" % (args.natoms or loaded[0][2]["natoms"] or "?"),
        "\\def\\platMac{%g}\n" % mac,
        "\\def\\platOrder{%d}\n" % order,
        "\\def\\platFixedTgt{%d}\n" % fixed_tgt,
        "\\def\\platFixedSrc{%d}\n" % fixed_src,
        "\\def\\platRepeats{%d}\n" % nrep,
        # The rank count differs BETWEEN series here -- that is the point of the
        # figure -- so the shared note would be wrong. Each series names its own.
        "\\def\\platMachine{%s}\n" % (
            fmm_csv.machine_note(args.machine, None).replace(
                "; the rank count is not recorded in the source CSV",
                "; each series names its own rank count")
            if len(ranks) > 1
            else fmm_csv.machine_note(args.machine, ranks.pop())),
    ]
    with open(reftex, "w") as fh:
        fh.write(localise("".join(ref_buf), args.tag))

    colordefs = "\n".join("\\definecolor{%s}{HTML}{%s}" % (n, h)
                          for n, h in RAMP[:len(loaded)])
    with open(fig, "w") as fh:
        fh.write(localise(FIGURE_TEMPLATE
                          .replace("COLORDEFS", colordefs)
                          .replace("PANELS", panels), args.tag))

    rows = []
    print("grid-wide optimum per platform:")
    for lab, grid, info in loaded:
        ordered = sorted(grid.values(), key=lambda d: d["time"])
        b, second = ordered[0], ordered[1]
        margin = second["time"] / b["time"] - 1.0
        sp = info["spread"]
        rows.append("%s & %d & %d & %.3f & %.1f\\%% & %s \\\\\n"
                    % (lab, b["sleaf"], b["tleaf"], b["time"], 100 * margin,
                       "---" if sp is None else "%.1f\\%%" % (100 * sp)))
        print("   %-28s %3d/%-5d %7.3f s   runner-up %d/%d +%.1f%%"
              % (lab, b["sleaf"], b["tleaf"], b["time"],
                 second["sleaf"], second["tleaf"], 100 * margin))
    with open(tab, "w") as fh:
        fh.write(localise(TABLE_TEMPLATE.replace("ROWS", "".join(rows)), args.tag))

    print("\nleft panel  : source axis at fixed tgt = %d" % fixed_tgt)
    for (lab, _), (x, y) in zip(src_prof, src_min):
        print("   %-28s min at src %d" % (lab, x))
    print("right panel : target axis at fixed src = %d" % fixed_src)
    for (lab, _), (x, y) in zip(tgt_prof, tgt_min):
        print("   %-28s min at tgt %d" % (lab, x))
    print("\nwrote %s\n      %s\n      %s\n      %s\n      %s"
          % (src_dat, tgt_dat, reftex, fig, tab))


if __name__ == "__main__":
    sys.exit(main())
