#!/usr/bin/env python3
"""
End-to-end pipeline time: the stock CPU/LIS baseline against the best local
CUDA configuration, for every molecule that was measured on the local system.

Unlike the other plot_*.py scripts this one does not read a bench_sweep.py
bench_runs.csv. The runs it plots were collected by hand after those sweeps, so
its input is a small CSV of raw per-run times (milliseconds, as the NGPB run
report prints them) that lives beside the generated data:

    figures/data/total_time_runs.csv

Writes, relative to the thesis directory:
    figures/data/<tag>.dat        one row per molecule, one column pair per config
    figures/data/<tag>_ref.tex    reference values as macros
    figures/<tag>.tex             the figure, \\input-able like the others
    figures/<tag>_table.tex       the accompanying table
"""

import argparse
import csv
import math
import os
import statistics

# One row per molecule in the order they appear in the other chapter figures
# (figures/energy_methods and figures/solver_bench both run 1CCM, 6VYB, 1VSZ),
# so a reader flipping between them does not have to re-find the columns.
MOLECULE_ORDER = ["1CCM", "6VYB", "1VSZ"]

# The atom count goes on the x axis rather than in the caption, same as
# figures/energy_methods: the three groups are three problem sizes, and without
# it the tallest group reads as the same work taking longer.
ATOMS = {"1CCM": "642", "6VYB": "44\\,495", "1VSZ": "14\\,299"}

# Orange is the unaccelerated reference everywhere else in the chapter (LIS in
# figures/solver_bench, the CPU path in figures/energy_methods) and the dark
# blue is the tuned/best configuration in both. Keeping that mapping here means
# the final figure needs no relearning.
CONFIGS = [
    ("baseline",  "CPU baseline (LIS)",  "totalbase", "D95F02"),
    ("optimized", "best CUDA config",    "totalbest", "2C5F8D"),
]

# What the optimized bar actually ran, per molecule. These are the winners of
# the earlier sections, not a fresh sweep, so they are recorded rather than
# derived -- the source CSV carries times only.
BEST_CONFIG = {
    "1CCM": "the naive $O(NM)$ kernel",
    "6VYB": "the FMM at $P = 11$, $\\theta = 0.4$, "
            "$n_{leaf,src} = 16$, $n_{leaf,tgt} = 1024$",
    "1VSZ": "the FMM at $P = 7$, $\\theta = 0.3$, "
            "$n_{leaf,src} = 16$, $n_{leaf,tgt} = 512$",
}


def read_runs(path):
    """{molecule: {config: [seconds, ...]}} from the hand-collected CSV."""
    out = {}
    with open(path, newline="") as fh:
        # The file is commented for the reader; csv has no comment support.
        rows = csv.DictReader(l for l in fh if not l.lstrip().startswith("#"))
        for r in rows:
            times = [float(r[c]) / 1000.0 for c in rows.fieldnames
                     if c.startswith("run") and (r.get(c) or "").strip()]
            out.setdefault(r["molecule"], {})[r["config"]] = sorted(times)
    return out


def stats(times):
    """Median plus the whisker lengths, which is what pgfplots wants: the error
    bars are drawn as offsets from the median, not as absolute endpoints."""
    med = statistics.median(times)
    return med, med - times[0], times[-1] - med


def fmt(x):
    return "{:.6g}".format(x)


def seconds_label(x):
    """Bar labels carry one significant figure more than the eye needs, so that
    1.17 and 1.43 stay distinguishable in the 1CCM group where the bars do
    not."""
    if x < 10:
        return "{:.2f}".format(x)
    if x < 100:
        return "{:.1f}".format(x)
    return "{:.0f}".format(x)


def write_dat(path, molecules, data):
    cols = ["molecule"]
    for key, _, _, _ in CONFIGS:
        cols += [key, key + "_em", key + "_ep", key + "_lbl"]
    with open(path, "w") as fh:
        fh.write(" ".join(cols) + "\n")
        for mol in molecules:
            cells = [mol]
            for key, _, _, _ in CONFIGS:
                med, em, ep = stats(data[mol][key])
                cells += [fmt(med), fmt(em), fmt(ep), seconds_label(med)]
            fh.write(" ".join(cells) + "\n")


def write_ref(path, sfx, molecules, data, repeats, machine, ranks):
    speedups = {m: statistics.median(data[m]["baseline"])
                   / statistics.median(data[m]["optimized"])
                for m in molecules}
    best = max(speedups, key=speedups.get)
    cfg = " ".join(
        "The optimized {} run used {}.".format(m, BEST_CONFIG[m])
        for m in molecules if m in BEST_CONFIG)
    with open(path, "w") as fh:
        fh.write("% generated by scripts/plot_total_time.py -- do not edit\n")
        for name, val in [
            ("totalMolecules", ", ".join(molecules)),
            ("totalRepeats", str(repeats)),
            ("totalBestSpeedup", "{:.2f}".format(speedups[best])),
            ("totalBestMolecule", best),
            ("totalMachine", " Measured on {} with {} MPI ranks.".format(machine, ranks)),
            ("totalConfig", " " + cfg),
        ]:
            fh.write("\\def\\{}{}{{{}}}\n".format(name, sfx, val))


def write_figure(path, tag, sfx, molecules, data, ymin, ymax, ytick):
    label = tag.replace("_", "-")
    dat = "figures/data/{}.dat".format(tag)
    xticklabels = ",".join(
        "{{{}\\\\{{\\scriptsize {} atoms}}}}".format(m, ATOMS[m])
        if m in ATOMS else "{{{}}}".format(m)
        for m in molecules)

    plots = []
    shifts = [-7.0, 7.0]
    for (key, legend, color, _), shift in zip(CONFIGS, shifts):
        plots.append(
            "  \\addplot+[\n"
            "    ybar, bar shift={shift}pt, fill={c}, draw={c}!70!black, line width=0.4pt,\n"
            "    nodes near coords, point meta=explicit symbolic,\n"
            "    error bars/.cd, y dir=both, y explicit,\n"
            "  ] table[x=molecule, y={k}, y error minus={k}_em, y error plus={k}_ep,\n"
            "          meta={k}_lbl] {{{dat}}};\n"
            "  \\addlegendentry{{{leg}}}".format(
                shift=shift, c=color, k=key, dat=dat, leg=legend))

    # The speedup is the payload of this figure, so it is drawn rather than left
    # for the reader to divide out. Not an arrow: on a log axis a double arrow
    # spanning the two bar tops is exactly as tall as the ratio it annotates,
    # which for 1CCM is 2 mm and unlabellable. And not stacked over the optimized
    # bar either -- the label is wider than the 13pt bar, so centered there it
    # overhangs onto the baseline bar next to it. It goes above the TALLER of the
    # pair, centered on the group, where it clears both bars and both value
    # labels whichever way round the pair happens to be.
    marks = []
    for mol in molecules:
        med_b = statistics.median(data[mol]["baseline"])
        med_o = statistics.median(data[mol]["optimized"])
        marks.append(
            "  \\node[font=\\scriptsize\\bfseries, color=totalbest, anchor=south,\n"
            "        inner sep=1pt, fill=white, fill opacity=0.85, text opacity=1]\n"
            "    at ([yshift=15pt] axis cs:{m},{y}) "
            "{{{s:.2f}$\\times$}};".format(
                m=mol, y=fmt(max(med_b, med_o)), s=med_b / med_o))

    colors = "\n".join("\\definecolor{{{}}}{{HTML}}{{{}}}".format(c, h)
                       for _, _, c, h in CONFIGS)

    with open(path, "w") as fh:
        fh.write(r"""% ------------------------------------------------------------------------
%  End-to-end pipeline time: CPU baseline vs the best local CUDA configuration.
%  Generated by scripts/plot_total_time.py -- regenerate rather than edit.
%  Include with \input{figures/TAG}
%  Needs \usepackage{pgfplots} in the preamble.
% ------------------------------------------------------------------------
\input{figures/data/TAG_ref}

\pgfplotsset{compat=1.16}

COLORS

\begin{figure}[!htb]
\centering
\begin{tikzpicture}
\begin{axis}[
    ybar,
    % The speedup annotation sits 15pt above the taller bar of each pair, which
    % is itself topped by a value label 4pt above the whisker -- more headroom
    % than ymax reliably covers.
    clip=false,
    width=13.1cm, height=6.8cm,
    bar width=13pt,
    enlarge x limits=0.30,
    % The three molecules span 500x end to end, so a shared linear axis would
    % flatten 1CCM onto the baseline. log origin y=infty is what makes the bars
    % start at ymin instead of at 1, where ybar puts them on a log axis by
    % default -- without it the 1CCM bars would hang below the frame.
    ymode=log, log origin y=infty,
    ymin=YMIN, ymax=YMAX,
    ytick={YTICK},
    % Wall clock gets read as wall clock; the exponents would make a reader
    % translate before comparing.
    log ticks with fixed point,
    ylabel={total run time [s]},
    ylabel style={font=\footnotesize},
    symbolic x coords={XCOORDS},
    xtick=data,
    xticklabels={XTICKLABELS},
    xticklabel style={font=\footnotesize, align=center},
    tick label style={font=\scriptsize},
    ymajorgrids=true,
    major grid style={black!12},
    % -0.22, not the -0.16 of figures/solver_bench: the tick labels here are two
    % lines, and the legend has to clear the atom count as well as the name.
    legend style={
      at={(0.5,-0.22)}, anchor=north, draw=none,
      legend columns=2, font=\footnotesize, column sep=0.8em,
    },
    % Run-to-run spread is well under a percent, so the whisker is under a
    % millimeter. Caps nearly as wide as the bar are what make it read as an
    % error bar rather than a stray tick. rotate=90 is required: pgfplots draws
    % the cap perpendicular to the error direction on its own, but any mark size
    % given here clobbers that and the cap then renders vertically.
    error bars/error bar style={black!85, line width=0.8pt},
    error bars/error mark options={
      mark size=3pt, rotate=90, line width=0.8pt, black!85,
    },
    every node near coord/.append style={
      font=\tiny, color=black!55, anchor=south, yshift=4pt,
    },
]
PLOTS

MARKS

\end{axis}
\end{tikzpicture}

\caption[Total pipeline time]{\textbf{End-to-end cost of the whole NGPB
    pipeline on \totalMoleculesSFX{}.} Median total run time over
    \totalRepeatsSFX{} runs on a logarithmic axis, whiskers spanning fastest to
    slowest; the gray figure above each bar is that median in seconds, the blue
    one the speedup over the baseline. The baseline is the stock CPU pipeline,
    LIS and \texttt{energy\_method\,=\,0}; the optimized bar is the tuned AMGX
    plus the best energy method for that molecule, listed in
    Table~\ref{TABREF}.\totalMachineSFX}
\label{fig:TAGLABEL}
\end{figure}
""".replace("TABREF", "tab:" + label)
   .replace("TAGLABEL", label)
   .replace("TAG", tag)
   .replace("COLORS", colors)
   .replace("YMIN", fmt(ymin)).replace("YMAX", fmt(ymax))
   .replace("YTICK", ",".join(fmt(t) for t in ytick))
   .replace("XCOORDS", ",".join(molecules))
   .replace("XTICKLABELS", xticklabels)
   .replace("PLOTS", "\n".join(plots))
   .replace("MARKS", "\n".join(marks))
   .replace("SFX", sfx))


def write_table(path, tag, sfx, molecules, data):
    label = "tab:" + tag.replace("_", "-")
    lines = []
    for i, mol in enumerate(molecules):
        if i:
            lines.append("\\midrule")
        med_b = statistics.median(data[mol]["baseline"])
        med_o = statistics.median(data[mol]["optimized"])
        for j, (key, legend, _, _) in enumerate(CONFIGS):
            med, em, ep = stats(data[mol][key])
            name = mol if j == 0 else ""
            # Only the optimized row carries a speedup; 1.00x on the baseline
            # row would be a number the reader has to discard.
            rel = "" if j == 0 else "{:.2f}$\\times$".format(med_b / med_o)
            lines.append(
                "{} & {} & {:.3f} & {:.3f} & {:.3f} & {} \\\\".format(
                    name, legend, med, med - em, med + ep, rel))
    with open(path, "w") as fh:
        fh.write(r"""% generated by scripts/plot_total_time.py -- do not edit
\begin{table}[!htb]
\centering
\footnotesize
\caption[Total pipeline time]{\textbf{End-to-end cost of the whole NGPB
    pipeline.} Median total run time over \totalRepeatsSFX{} runs, with the
    fastest and slowest of those runs alongside it, and the speedup of the
    optimized configuration over the baseline for that molecule. The baseline is
    LIS and the CPU energy path (\texttt{energy\_method\,=\,0}), including the
    host-side optimizations of
    Sections~\ref{sec:evaluation-results-create-markers}
    and~\ref{sec:evaluation-results-bimpp}; every optimized run used AMGX with
    the tuned configuration.\totalConfigSFX\totalMachineSFX}
\label{TABLABEL}
\begin{tabular}{llrrrr}
\toprule
& & \multicolumn{3}{c}{total [s]} & \\
\cmidrule(lr){3-5}
molecule & configuration & median & fastest & slowest & speedup \\
\midrule
BODY
\bottomrule
\end{tabular}
\end{table}
""".replace("TABLABEL", label)
   .replace("BODY", "\n".join(lines))
   .replace("SFX", sfx))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--runs", default="thesis/figures/data/total_time_runs.csv")
    ap.add_argument("--tag", default="total_time")
    ap.add_argument("--thesis", default="thesis")
    ap.add_argument("--repeats", type=int, default=3)
    ap.add_argument("--ranks", type=int, default=4)
    ap.add_argument("--machine",
                    default="the local system (Table~\\ref{tab:test-systems})")
    args = ap.parse_args()

    data = read_runs(args.runs)
    molecules = [m for m in MOLECULE_ORDER if m in data]
    molecules += [m for m in data if m not in molecules]

    lo = min(min(v) for m in molecules for v in data[m].values())
    hi = max(max(v) for m in molecules for v in data[m].values())
    # A third of a decade of floor below the shortest bar, so that bar still has
    # visible height instead of sitting flat on the frame, and 0.4 of a decade
    # of headroom above the tallest for the two rows of annotation. Both are
    # offsets from the enclosing decade, not from the data, so the ticks stay on
    # round powers of ten whatever the times happen to be.
    decade_lo = math.floor(math.log10(lo))
    decade_hi = math.ceil(math.log10(hi))
    ymin = 10 ** (decade_lo - 0.3)
    ymax = 10 ** (decade_hi + 0.4)
    ytick = [10 ** e for e in range(decade_lo, decade_hi + 1)]

    sfx = "".join(c for c in args.tag if c.isalpha())
    d = os.path.join(args.thesis, "figures")
    write_dat(os.path.join(d, "data", args.tag + ".dat"), molecules, data)
    write_ref(os.path.join(d, "data", args.tag + "_ref.tex"), sfx, molecules,
              data, args.repeats, args.machine, args.ranks)
    write_figure(os.path.join(d, args.tag + ".tex"), args.tag, sfx, molecules,
                 data, ymin, ymax, ytick)
    write_table(os.path.join(d, args.tag + "_table.tex"), args.tag, sfx,
                molecules, data)
    print("wrote {0}/data/{1}.dat, {0}/data/{1}_ref.tex, {0}/{1}.tex, "
          "{0}/{1}_table.tex".format(d, args.tag))


if __name__ == "__main__":
    main()
